## Q1- construct 1d numpy array, 2d numpy array,3d numpy array.

In [1]:
import numpy as np

In [4]:
#1d
z = np.arange(1, 13)
print(z)

#2d
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
d2 = arr.reshape(3, 4)

print(d2)



#3d
d3 = arr.reshape(2, 2, 3)
print(d3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Q2- Write a NumPy program to test whether any of the elements of a given array is non-zero. Hint use any()

In [6]:
# x contain number except zeros
x = np.array([0, 0, 1, 0,])
print(x,np.any(x))


z = np.array([0, 0, 0, 0])
print(z,np.any(z))

[0 0 1 0] True
[0 0 0 0] False


### Q3- Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [7]:
array1=np.zeros(10)
print(array1)


array2=np.ones(10)
print(array2)


array3=5*np.ones(10)
print(array3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## Q4- Write a NumPy program to create an array of 10 zeros 3d

In [9]:
arr_3d = np.zeros( (3, 4, 5) )
print(arr_3d)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


### Q5- Write a NumPy program to create an array of the integers from 30 to 70.

In [10]:
z = np.arange(30, 71)
print(z)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


Q6- Write a NumPy program to create a 3x3 identity matrix.

In [11]:
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q7- Write a NumPy program to generate a random number between 0 and 1.

In [13]:
x = np.random.random(1)
print(x)

[0.52529437]


Q8- Write a NumPy program to create a 3X4 array using and iterate over it.

In [17]:
Z = np.arange(1,13)
print(Z)

Z=Z.reshape((3, 4))
print(Z)
for i in np.nditer(Z):
  print(i,end=" ")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1 2 3 4 5 6 7 8 9 10 11 12 

Q9- Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and
inside 0.

In [18]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
